# © 2019 Serokell <hi@serokell.io>
# © 2019 Lars Jellema <lars.jellema@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

env:
  CDN_DISTRIBUTION_ID: E13UN1J1JFIWUZ
  CDN_BUCKET: s3://nixfmt.serokell.io

steps:
  - label: reuse lint
    commands:
      - nix shell .#packages.x86_64-linux.reuse -c reuse lint
  - label: nix-build
    commands:
      - nix build .#nixfmt-static | cachix push nixfmt
      - nix build .#nixfmt-deriver | cachix push nixfmt
  - label: build web demo
    commands:
      - set -o pipefail; nix build .#nixfmt-webdemo | cachix push nixfmt
  - wait
  - label: deploy web demo
    branches: master
    commands:
      - nix build .#nixfmt-webdemo
      - nix shell .#awscli -c
          aws s3 cp --recursive result/ "$CDN_BUCKET"
      # delete files that don't exist anymore, use `--size-only` so behavior won't depend on local file timestamps
      - nix shell .#awscli -c
          aws s3 sync --delete --size-only result/ "$CDN_BUCKET"
      - nix shell .#awscli -c
          aws cloudfront create-invalidation --distribution-id "$CDN_DISTRIBUTION_ID" --paths '/*'
