# © 2019 Serokell <hi@serokell.io>
# © 2019 Lars Jellema <lars.jellema@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

env:
  CDN_DISTRIBUTION_ID: E13UN1J1JFIWUZ
  CDN_BUCKET: s3://nixfmt.serokell.io

steps:
  - label: nix-build
    commands:
      - nix-build -A nixfmt-static | cachix push nixfmt
      - nix-build -A nixfmt-deriver | cachix push nixfmt
  - label: build web demo
    commands:
      - nix-build -A nixfmt-webdemo | cachix push nixfmt
  - wait
  - label: deploy web demo
    branches: master
    commands:
      - nix-build -A nixfmt-webdemo
      - nix run -f . awscli -c
          aws s3 cp --recursive result/ "$CDN_BUCKET"
      # delete files that don't exist anymore, use `--size-only` so behavior won't depend on local file timestamps
      - nix run -f . awscli -c
          aws s3 sync --delete --size-only result/ "$CDN_BUCKET"
      - nix run -f . awscli -c
          aws cloudfront create-invalidation --distribution-id "$CDN_DISTRIBUTION_ID" --paths '/*'
