name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26

      - name: reuse lint
        run: nix-build -A packages.reuse && result/bin/reuse lint

      - name: build nixfmt
        run: nix-build
        if: success() || failure()

      - name: run tests
        run: nix-shell --run ./test/test.sh
